### ISSUE TITLE
[Bug]: Warning in yarn dev

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/ecommerce-integration-boilerplate#56]
### Actual Behavior

After running `yarn dev` this warning will be shown in console print:  

ERROR  (node:28690) [DEP0128] DeprecationWarning: Invalid 'main' field in 'node_modules/@vue-storefront/nuxt-theme/package.json' of 'lib/module.js'. Please either fix that or report it to the module author
[dev:theme] (Use `node --trace-deprecation ...` to show where the warning was created)

### What version of __replace_me__ integration are you using?

any

### What version of Node.js are you using?

any

### What browser (and version) are you using?

any

### What operating system (and version) are you using?

any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
This issue has [already been fixed](https://github.com/vuestorefront/vue-storefront/pull/6639/files#diff-9ab9b08da18299ae96a87ee99580d106b1c8f41ee7b3bba5769e71ca35373497R5) in the main repository and will be available in the next minor release.

Nuxt reports this as an error for some reason, but in reality, it's just a warning that you can ignore for now.

**Comment by samberrry** [comment]
thanks Filip.
